apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "hive-metastore.fullname" . }}
  labels: 
    app: {{ template "hive-metastore.name" . }}
    chart: {{ template "hive-metastore.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hive-metastore
spec:
  selector:
     matchLabels:
      app: {{ template "hive-metastore.name" . }}
      release: {{ .Release.Name }}
      component: hive-metastore
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ template "hive-metastore.name" . }}
        release: {{ .Release.Name }}
        component: hive-metastore
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hive-metastore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "hive-metastore.name" . }}-config
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: thrift
              containerPort: 9083
          livenessProbe:
            tcpSocket:
              port: 9083
            initialDelaySeconds: 30
            periodSeconds: 60
          volumeMounts:
          - name: config-volume
            mountPath: /opt/hive-metastore/conf/metastore-site.xml
            subPath: metastore-site.xml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
